/**
 * Type-safe USDC Payment — Hybrid viem + EIP-1193 (Client-side)
 *
 * Uses viem for type-safe ABI encoding only (tree-shakeable to ~3 KB).
 * Transaction sending and chain validation use raw EIP-1193 provider calls
 * to minimize bundle size while maintaining compile-time type safety
 * on the critical ABI encoding path.
 *
 * Receipt polling is server-side only (see `src/lib/web3/receipt.ts`).
 *
 * @module pay
 */

import {
  encodeFunctionData,
  type Address,
} from 'viem';
import { parseAbi } from 'viem';

// ─── Configuration ─────────────────────────────────────────────
const USDC_ADDRESS = '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' as Address;
const USDC_DECIMALS = 6;

/**
 * Receiver address sourced from env var at build time (Astro/Vite).
 * Falls back to a hardcoded address if the env var is not set.
 */
const RECEIVER_ADDRESS: Address = (
  import.meta as unknown as { env?: { PUBLIC_RECEIVER_ADDRESS?: string } }
).env?.PUBLIC_RECEIVER_ADDRESS
  ? (`${(import.meta as unknown as { env: { PUBLIC_RECEIVER_ADDRESS: string } }).env.PUBLIC_RECEIVER_ADDRESS}` as Address)
  : '0x94Ac0Cbf9188E31979Ad1434d86Cdc75ddBEc10c';

/** Number of USDC required to unlock all content. */
export const PRICE_USDC = 3;

/** Ethereum mainnet chain ID (hex). */
const MAINNET_CHAIN_ID = '0x1';

// ─── Types ─────────────────────────────────────────────────────

/** A provider compatible with EIP-1193 (what EIP-6963 wallets expose). */
export type WalletProvider = {
  request(args: { method: string; params?: unknown[] }): Promise<unknown>;
  on(event: string, handler: (...args: unknown[]) => void): void;
  removeListener(event: string, handler: (...args: unknown[]) => void): void;
};

/** Transaction hash type. */
export type TxHash = `0x${string}`;

// ─── Minimal ABI (type-safe, tree-shakeable) ───────────────────

const transferAbi = parseAbi([
  'function transfer(address to, uint256 amount) returns (bool)',
]);

// ─── Core Functions ────────────────────────────────────────────

/**
 * Encode a USDC `transfer(to, amount)` calldata using viem's type-safe ABI.
 * This is the critical type-safety boundary: `parseAbi` + `encodeFunctionData`
 * enforce correct function name and argument types at compile time.
 *
 * @param to - Recipient Ethereum address.
 * @param amount - Number of USDC tokens (human-readable, e.g. 3).
 * @returns Encoded calldata string (`0x...`).
 */
export function encodeUSDCTransfer(to: Address, amount: number): `0x${string}` {
  const rawAmount = BigInt(amount) * 10n ** BigInt(USDC_DECIMALS);
  return encodeFunctionData({
    abi: transferAbi,
    functionName: 'transfer',
    args: [to, rawAmount],
  });
}

/**
 * Validate the wallet's current chain and prompt a switch to Ethereum mainnet
 * if necessary. Uses raw EIP-1193 provider calls to minimize bundle size.
 *
 * @param provider - EIP-1193 compatible wallet provider.
 * @throws If the user rejects the chain switch prompt.
 */
export async function ensureMainnet(provider: WalletProvider): Promise<void> {
  const chainId = (await provider.request({ method: 'eth_chainId' })) as string;

  if (chainId !== MAINNET_CHAIN_ID) {
    try {
      await provider.request({
        method: 'wallet_switchEthereumChain',
        params: [{ chainId: MAINNET_CHAIN_ID }],
      });
    } catch {
      throw new Error(
        'Ethereum\u30e1\u30a4\u30f3\u30cd\u30c3\u30c8 (Chain ID: 1) \u306b\u5207\u308a\u66ff\u3048\u3066\u304f\u3060\u3055\u3044\u3002'
      );
    }
  }
}

/**
 * Send 3 USDC from the connected wallet to the configured receiver.
 *
 * Uses raw EIP-1193 provider calls for transaction sending (no viem
 * WalletClient needed). The calldata is generated by viem's
 * `encodeFunctionData` with a typed ABI, ensuring compile-time
 * correctness of function name and argument types.
 *
 * After sending, the caller should POST to `/api/unlock` with the hash
 * for server-side receipt verification.
 *
 * @param provider - EIP-1193 compatible wallet provider (from EIP-6963 discovery).
 * @returns The transaction hash.
 */
export async function payThreeUsdc(provider: WalletProvider): Promise<TxHash> {
  // Validate chain before sending
  await ensureMainnet(provider);

  // Request accounts (may trigger wallet popup)
  const accounts = (await provider.request({
    method: 'eth_requestAccounts',
  })) as string[];

  const account = accounts[0] as Address;

  // Type-safe ABI encoding via viem
  const data = encodeUSDCTransfer(RECEIVER_ADDRESS, PRICE_USDC);

  // Send transaction via raw EIP-1193
  const hash = (await provider.request({
    method: 'eth_sendTransaction',
    params: [{ from: account, to: USDC_ADDRESS, data }],
  })) as TxHash;

  return hash;
}

// ─── Wallet Event Listeners ────────────────────────────────────

/**
 * Subscribe to account change events on the wallet provider.
 * If the user disconnects (accounts array becomes empty), the callback
 * is invoked with `null`.
 */
export function onAccountsChanged(
  provider: WalletProvider,
  onAccountsChanged: (accounts: string[] | null) => void
): () => void {
  const handler = (accounts: unknown) => {
    const accs = accounts as string[];
    onAccountsChanged(accs.length === 0 ? null : accs);
  };
  provider.on('accountsChanged', handler);
  return () => provider.removeListener('accountsChanged', handler);
}

/**
 * Subscribe to chain change events. The recommended behavior is to
 * reload the page so the UI reflects the new network state.
 */
export function onChainChanged(
  provider: WalletProvider,
  onChainChanged: () => void
): () => void {
  const handler = () => onChainChanged();
  provider.on('chainChanged', handler);
  return () => provider.removeListener('chainChanged', handler);
}

// ─── Exports for Server-Side Use ───────────────────────────────
export { USDC_ADDRESS, RECEIVER_ADDRESS };
